config/routes.rb
Rails.application.routes.draw do
  root 'songs#new'
  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  validates_presence_of :artist, :title

  def swapper(string, swear_set, user_input)
    swear_set.each do |swear|
      string.gsub!(/\b(#{swear})\b/i, "<b>#{user_input.sample}</b>")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    fetcher = Lyricfy::Fetcher.new
    begin
      @lyrics = fetcher.search("#{@song.artist}", "#{@song.title}")
      @lyrics = @lyrics.body("<br>")
      @song.lyrics = @lyrics
      if @song.save
        redirect_to edit_song_path(@song)
      else
        render :new, :status => :unprocessable_entity
      end
    rescue
      flash.now[:error] = "Song not found"
      render :new
    end
  end

  def index
    redirect_to root_path
  end

  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def edit
    @song = Song.find(params[:id])
    if @song.nouns.present?
      redirect_to @song
    end
  end

  def update
    @song = Song.find(params[:id])
    @song.update_attributes(song_params)


    nouns = @song.nouns.split
    adjectives = @song.adjectives.split
    people = @song.people.split
    verbs = @song.verbs.split

    @song.swapper(@song.lyrics, "#{ENV["nouns"]}".split, nouns) 
    @song.swapper(@song.lyrics, "#{ENV["adjectives"]}".split, adjectives) 
    @song.swapper(@song.lyrics, "#{ENV["people"]}".split, people) 
    @song.swapper(@song.lyrics, "#{ENV["verbs"]}".split, verbs) 

    if @song.save
      redirect_to @song
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  private

  def song_params
    params.require(:song).permit(:artist, :title, :lyrics, :nouns, :adjectives, :people, :verbs)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MAAD Libs</title>
    <%= csrf_meta_tags %>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Rap Mad Libs">
        <meta name="author" content="Ben Ricker">

        <!-- Bootstrap Core CSS -->
        <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Theme CSS -->
        <link href="css/freelancer.min.css" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body id="page-top" class="index">

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href= <%= root_path %>>MAAD Libs</a>
            </div>
        </div>
    </nav>

    <%= yield %>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>is this open source?</h3>
                        <p>Yes, please help me improve it</p>
                        <a href="https://github.com/BGRicker/maadlibs" class="btn-social btn-outline"><i class="glyphicon glyphicon-fire"></i></a>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>I need more Ben</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="http://www.twitter.com/goodtimehaver" class="btn-social btn-outline"><i class="glyphicon glyphicon-heart-empty"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/benjamin-ricker-b371a423" class="btn-social btn-outline"><i class="glyphicon glyphicon-eye-open"></i></a>
                            </li>
                            <li>
                                <a href="https://www.github.com/bgricker" class="btn-social btn-outline"><i class="glyphicon glyphicon-sunglasses"></i></a>
                            </li>
                            <li>
                                <a href="http://www.bgricker.com" class="btn-social btn-outline"><i class="glyphicon glyphicon-home"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>I need to sue you</h3>
                        <p> Alright, email me: yo@bgricker.com</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        "I'll never tell you to get down, it's all about coming up" Ice Cube
                    </div>
                </div>
            </div>
        </div>
    </footer>

  <!-- Plugin JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

  <!-- Contact Form JavaScript -->
  <script src="app/assets/javascript/jqBootstrapValidation.js"></script>
  <script src="app/assets/javascript/contact_me.js"></script>

  <!-- Theme JavaScript -->
  <script src="app/assets/javascript/freelancer.min.js"></script>

  </body>

</html>

app/views/songs/edit.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-text">
          <span class="name">MAAD Libs</span>
          <span class="skills">Choose a bunch of words without punctuation that fit their categories to replace their swears below</span><br><br>
          <span class="skills">Example: NOUNS: "pizza Fieri basketball" will add the possibility that "pizza," "Fieri," and "basketball" will appear in place of noun swears</span>
        </div>
      </div>
    </div>
  </div>
</header>

<%= simple_form_for @song do |f| %>
  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2><%= @song.artist %> - <%= @song.title %></h2>
          <hr class="star-primary">
          <% if flash[:error] %>
            <h4><div class="error"><%= flash.now[:error] %></div></h4>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <form name="sentMessage" id="contactForm" novalidate>

            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label></label>
                <%= f.input :nouns, input_html: { type: 'text', class: "form-control", placeholder: "Nouns", id: "name" } %>
                <p class="help-block text-danger"></p>
              </div>
            </div>

            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label></label>
                <%= f.input :adjectives, input_html: { type: 'text', class: "form-control", placeholder: "Adjectives", id: "name" } %>
                <p class="help-block text-danger"></p>
              </div>
            </div>

            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label></label>
                <%= f.input :people, input_html: { type: 'text', class: "form-control", placeholder: "People", id: "name" } %>
                <p class="help-block text-danger"></p>
              </div>
            </div>

            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label></label>
                <%= f.input :verbs, input_html: { type: 'text', class: "form-control", placeholder: "Verbs", id: "name" } %>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>

            <div id="success"></div>
            <div class="row">
              <div class="form-group col-xs-12">
                <%= f.submit class: 'btn btn-success btn-lg' %>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <% if @song.errors.any? %>
    <% redirect_to new_song_path %>
  <% end %>
<% end %>

app/views/songs/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <header>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="intro-text">
            <span class="name">MAAD Libs</span>
            <span class="skills">Mad Libs with Songs of Your Choice to Replace Swears</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2>Enter Your Song</h2>
          <hr class="star-primary">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <form name="sentMessage" id="contactForm" novalidate>
            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Name</label>
                <input type="text" class="form-control" placeholder="Artist" id="name" required data-validation-required-message="Please enter artist name">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="row control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Email Address</label>
                <input type="email" class="form-control" placeholder="Song Title" id="email" required data-validation-required-message="Please enter song name.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="row">
              <div class="form-group col-xs-12">
                <button type="submit" class="btn btn-success btn-lg">Send</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  </body>

</html>

app/views/songs/new.html.erb
<!DOCTYPE html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-93860600-1', 'auto');
  ga('send', 'pageview');
</script>

<html lang="en">

  <header>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="intro-text">
            <span class="name">MAAD Libs</span>
            <span class="skills">Mad Libs with Songs of Your Choice to Replace Swears</span>
          </div>
        </div>
      </div>
    </div>
  </header>



  <%= simple_form_for @song do |f| %>
    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2>Enter Your Song</h2>
            <hr class="star-primary">
            <% if flash[:error] %>
              <h4><div class="error"><%= flash.now[:error] %></div></h4>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <form name="sentMessage" id="contactForm" novalidate>
              <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                  <label>Artist</label>
                  <%= f.input :artist, input_html: { type: 'text', class: "form-control", placeholder: "Artist", id: "name" } %>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                  <label>Song Title</label>
                  <%= f.input :title, input_html: { type: 'text', class: "form-control", placeholder: "Song Title", id: "name" } %>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <br>
              <div id="success"></div>
              <div class="row">
                <div class="form-group col-xs-12">
                  <%= f.submit class: 'btn btn-success btn-lg' %>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <% if @song.errors.any? %>
      <% redirect_to new_song_path %>
    <% end %>
  <% end %>

  <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
  <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
      <i class="fa fa-chevron-up"></i>
    </a>
  </div>

  </body>

</html>

app/views/songs/show.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-text">
          <span class="name"><%= @song.title %></span>
          <span class="skills"><%= @song.artist %> </span>
        </div>
      </div>
    </div>
  </div>
</header>
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <p><%= "#{@song.lyrics}".html_safe %></p>
      </div class>
    </div class>
  </div class>
</section>

app/views/static_pages/index.html.erb
HIIIIII